name: CI

on:
  push:
    branches: [main, '**']
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  quality-gates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Use Node.js 20
        uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: 'yarn'

      - name: Guard against npm lockfile
        run: yarn ci:guard:lockfile

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Format check
        run: yarn -s format:check

      - name: Lint
        run: yarn -s lint

      - name: Type-check
        run: yarn -s tsc -p tsconfig.json --noEmit

      - name: Build
        run: yarn build

      - name: E2E smoke (curl)
        shell: bash
        run: |
          set -euo pipefail
          # Start preview in background
          (yarn preview >/dev/null 2>&1 &)
          # Wait for server
          for i in {1..20}; do
            if curl -sSf http://localhost:4000 >/dev/null; then break; fi; sleep 0.5;
          done
          # Root responds
          curl -sSf http://localhost:4000 >/dev/null
          # Head tags
          curl -s http://localhost:4000 | grep -q 'name="theme-color" media="(prefers-color-scheme: light)" content="#F5F5F7"'
          curl -s http://localhost:4000 | grep -q 'name="theme-color" media="(prefers-color-scheme: dark)" content="#1C1C1C"'
          curl -s http://localhost:4000 | grep -q 'rel="canonical" href="https://blanche-enterprise-trial.com/"'
          curl -s http://localhost:4000 | grep -q 'property="og:site_name" content="Blanche Enterprise Trial"'
          curl -s http://localhost:4000 | grep -q 'property="og:image" content="https://blanche-enterprise-trial.com/og-card.jpg"'
          curl -s http://localhost:4000 | grep -q 'name="twitter:image" content="https://blanche-enterprise-trial.com/og-card.jpg"'
          # Aux endpoints
          curl -sSf http://localhost:4000/robots.txt | grep -q 'Sitemap: https://blanche-enterprise-trial.com/sitemap.xml'
          curl -sSf http://localhost:4000/sitemap.xml | grep -q '<loc>https://blanche-enterprise-trial.com/</loc>'
          curl -sSf http://localhost:4000/manifest.json >/dev/null
          # Stop preview
          pkill -f "vite preview" || true

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

      # Optional: Enable Playwright later if desired
      # - name: Install Playwright browsers
      #   run: npx playwright install --with-deps
      # - name: E2E smoke + a11y
      #   run: yarn test:e2e
